#!/usr/bin/env python3
"""Extract the .text section from a COFF object, applying intra-section
REL32 relocations, so the blob is directly executable at any base address.
Prints section-relative offsets of external symbols in .text."""
import struct, sys

def main():
    obj_path, out_path = sys.argv[1], sys.argv[2]
    data = open(obj_path, "rb").read()

    machine, nsections, _, symtab_off, nsymbols, opt_hdr, _ = struct.unpack_from("<HHIIIHH", data, 0)
    assert machine == 0x8664, f"not AMD64 COFF: {machine:#x}"

    strtab_off = symtab_off + nsymbols * 18
    def sym_name(raw):
        if raw[:4] == b"\0\0\0\0":
            off = struct.unpack_from("<I", raw, 4)[0]
            end = data.index(b"\0", strtab_off + off)
            return data[strtab_off + off:end].decode()
        return raw.rstrip(b"\0").decode()

    sections = []  # (name, size_raw, ptr_raw, ptr_reloc, nreloc)
    shdr = 20 + opt_hdr
    for i in range(nsections):
        name, vsize, vaddr, sraw, praw, prel, plin, nrel, nlin, chars = \
            struct.unpack_from("<8sIIIIIIHHI", data, shdr + i * 40)
        sections.append((name.rstrip(b"\0").decode(), sraw, praw, prel, nrel))

    text_idx = next(i for i, s in enumerate(sections) if s[0] == ".text")
    name, sraw, praw, prel, nrel = sections[text_idx]
    text = bytearray(data[praw:praw + sraw])

    # symbols, index-aligned (aux entries occupy slots)
    indexed = []
    idx = 0
    while idx < nsymbols:
        raw = data[symtab_off + idx * 18: symtab_off + (idx + 1) * 18]
        value, secnum, typ, sclass, naux = struct.unpack_from("<IhHBB", raw, 8)
        indexed.append((sym_name(raw[:8]), value, secnum, sclass))
        for _ in range(naux):
            indexed.append(None)
        idx += 1 + naux

    # relocations on .text
    IMAGE_REL_AMD64_REL32 = 0x0004
    for r in range(nrel):
        va, symidx, rtype = struct.unpack_from("<IIH", data, prel + r * 10)
        s = indexed[symidx]
        assert s is not None, "reloc points at aux symbol"
        sname, svalue, ssec, sclass = s
        if rtype == IMAGE_REL_AMD64_REL32:
            if ssec - 1 != text_idx:
                sys.exit(f"unsupported: REL32 to symbol {sname} outside .text (section {ssec})")
            addend = struct.unpack_from("<i", text, va)[0]
            disp = svalue + addend - (va + 4)
            struct.pack_into("<i", text, va, disp)
        else:
            sys.exit(f"unsupported reloc type {rtype:#x} -> {sname}")

    open(out_path, "wb").write(text)

    IMAGE_SYM_CLASS_EXTERNAL = 2
    exported = [(s[0], s[1]) for s in indexed
                if s and s[2] - 1 == text_idx and s[3] == IMAGE_SYM_CLASS_EXTERNAL]
    for name, off in exported:
        print(f"{name} {off:#x}")

    # Optional third arg: emit a C header with the offsets for the runner.
    if len(sys.argv) > 3:
        with open(sys.argv[3], "w") as h:
            h.write("// generated by extract_text.py — symbol offsets into text.bin\n")
            for name, off in exported:
                h.write(f"#define {name.upper()}_OFF {off:#x}\n")

if __name__ == "__main__":
    main()
