// x86_64 harness: loads a raw .text blob generated by the Odin x64 backend into
// executable memory and calls into it. Built with `clang -arch x86_64`, so on
// Apple Silicon it runs under Rosetta 2.
//
// Two ABI modes, matching the target the blob was generated for:
//   default          — SysV (blob from -target:darwin_amd64/linux_amd64): plain calls.
//   -DWIN64_ABI      — Win64 (blob from -target:windows_amd64): ms_abi calls.
// Compile-time offsets come from text_syms.h (written by extract_text.py).
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/sysctl.h>

#include "text_syms.h"

#ifdef WIN64_ABI
#define ABI __attribute__((ms_abi))
#else
#define ABI
#endif

typedef long long (ABI *fn1)(long long);
typedef long long (ABI *fn2)(long long, long long);
typedef double    (ABI *fnmix)(double, long long, double, long long);
typedef long long (ABI *fn8)(long long, long long, long long, long long,
                             long long, long long, long long, long long);

typedef struct { long long a, b; }    Pair_II;
typedef struct { double x, y; }       Pair_DD;
typedef struct { long long i; double d; } Mixed;
typedef struct { long long a, b, c; } Big;
typedef struct { float a, b; }        Small_FF;
typedef struct { const char *data; long long len; } OdinString;

typedef long long (ABI *fn_pair_sum)(Pair_II);
typedef Pair_II   (ABI *fn_make_pair)(long long, long long);
typedef double    (ABI *fn_dd_dot)(Pair_DD, Pair_DD);
typedef Pair_DD   (ABI *fn_make_dd)(double, double);
typedef Mixed     (ABI *fn_mixed)(Mixed);
typedef long long (ABI *fn_big_sum)(Big);
typedef Big       (ABI *fn_make_big)(long long);
typedef float     (ABI *fn_ff)(Small_FF);
typedef long long (ABI *fn_str_bytes)(OdinString);

static int check(const char *what, long long got, long long want) {
    int ok = got == want;
    printf("%-32s = %lld (want %lld) %s\n", what, got, want, ok ? "OK" : "FAIL");
    return ok;
}

static int check_f(const char *what, double got, double want) {
    int ok = got == want;
    printf("%-32s = %g (want %g) %s\n", what, got, want, ok ? "OK" : "FAIL");
    return ok;
}

int main(int argc, char **argv) {
    const char *path = argc > 1 ? argv[1] : "text.bin";

    int translated = 0;
    size_t sz = sizeof(translated);
    sysctlbyname("sysctl.proc_translated", &translated, &sz, NULL, 0);
    printf("process: x86_64, rosetta-translated: %s, abi: %s\n",
           translated ? "yes" : "no",
#ifdef WIN64_ABI
           "win64");
#else
           "sysv");
#endif

    FILE *f = fopen(path, "rb");
    if (!f) { perror("fopen"); return 1; }
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    size_t map_size = (size_t)(size + 0xfff) & ~(size_t)0xfff;
    void *mem = mmap(NULL, map_size, PROT_READ | PROT_WRITE | PROT_EXEC,
                     MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (mem == MAP_FAILED) { perror("mmap rwx"); return 1; }
    if (fread(mem, 1, (size_t)size, f) != (size_t)size) { perror("fread"); return 1; }
    fclose(f);

    fn2   ros_add       = (fn2)  ((char *)mem + ROS_ADD_OFF);
    fn1   ros_sum       = (fn1)  ((char *)mem + ROS_SUM_OFF);
    fn1   ros_fib       = (fn1)  ((char *)mem + ROS_FIB_OFF);
    fnmix ros_mix       = (fnmix)((char *)mem + ROS_MIX_OFF);
    fn8   ros_many      = (fn8)  ((char *)mem + ROS_MANY_OFF);
    fn1   ros_call_many = (fn1)  ((char *)mem + ROS_CALL_MANY_OFF);

    int ok = 1;
    ok &= check("ros_add(2, 3)", ros_add(2, 3), 5);
    ok &= check("ros_add(1234567890123, -23)", ros_add(1234567890123LL, -23), 1234567890100LL);
    ok &= check("ros_sum(100)", ros_sum(100), 5050);
    ok &= check("ros_sum(1000000)", ros_sum(1000000), 500000500000LL);
    ok &= check("ros_fib(20)", ros_fib(20), 6765);
    ok &= check("ros_fib(30)", ros_fib(30), 832040);
    ok &= check_f("ros_mix(1.5, 2, 2.5, 4)", ros_mix(1.5, 2, 2.5, 4), 1.5*2 + 2.5*4);
    ok &= check("ros_many(1..8)", ros_many(1, 2, 3, 4, 5, 6, 7, 8),
                1 + 2*2 + 3*3 + 4*4 + 5*5 + 6*6 + 7*7 + 8*8);
    ok &= check("ros_call_many(10)", ros_call_many(10),
                10 + 2*11 + 3*12 + 4*13 + 5*14 + 6*15 + 7*16 + 8*17);

    // Aggregate classification tests.
    fn_pair_sum  ros_pair_sum  = (fn_pair_sum) ((char *)mem + ROS_PAIR_SUM_OFF);
    fn_make_pair ros_make_pair = (fn_make_pair)((char *)mem + ROS_MAKE_PAIR_OFF);
    fn_dd_dot    ros_dd_dot    = (fn_dd_dot)   ((char *)mem + ROS_DD_DOT_OFF);
    fn_make_dd   ros_make_dd   = (fn_make_dd)  ((char *)mem + ROS_MAKE_DD_OFF);
    fn_mixed     ros_mixed_f   = (fn_mixed)    ((char *)mem + ROS_MIXED_OFF);
    fn_big_sum   ros_big_sum   = (fn_big_sum)  ((char *)mem + ROS_BIG_SUM_OFF);
    fn_make_big  ros_make_big  = (fn_make_big) ((char *)mem + ROS_MAKE_BIG_OFF);
    fn_ff        ros_ff        = (fn_ff)       ((char *)mem + ROS_FF_OFF);
    fn_str_bytes ros_str_bytes = (fn_str_bytes)((char *)mem + ROS_STR_BYTES_OFF);
    fn2          ros_roundtrip = (fn2)         ((char *)mem + ROS_ROUNDTRIP_OFF);

    Pair_II  pii  = { 7, 35 };
    Pair_DD  v    = { 1.0, 2.0 }, w = { 3.0, 4.0 };
    Mixed    m0   = { 5, 1.5 };
    Big      big  = { 1, 2, 3 };
    Small_FF sff  = { 1.5f, 2.25f };
    OdinString s  = { "abc", 3 };

    ok &= check("ros_pair_sum({7,35})", ros_pair_sum(pii), 42);
    Pair_II mp = ros_make_pair(3, 4);
    ok &= check("ros_make_pair(3,4).a", mp.a, 3);
    ok &= check("ros_make_pair(3,4).b", mp.b, 4);
    ok &= check_f("ros_dd_dot({1,2},{3,4})", ros_dd_dot(v, w), 11.0);
    Pair_DD dd = ros_make_dd(1.5, 2.5);
    ok &= check_f("ros_make_dd(1.5,2.5).x", dd.x, 1.5);
    ok &= check_f("ros_make_dd(1.5,2.5).y", dd.y, 2.5);
    Mixed mr = ros_mixed_f(m0);
    ok &= check("ros_mixed({5,1.5}).i", mr.i, 10);
    ok &= check_f("ros_mixed({5,1.5}).d", mr.d, 4.5);
    ok &= check("ros_big_sum({1,2,3})", ros_big_sum(big), 6);
    Big mb = ros_make_big(9);
    ok &= check("ros_make_big(9).a+b+c", mb.a + mb.b + mb.c, 9 + 10 + 11);
    ok &= check_f("ros_ff({1.5,2.25})", (double)ros_ff(sff), 3.75);
    ok &= check("ros_str_bytes(\"abc\")", ros_str_bytes(s), 'a' + 'b' + 'c');
    // p={5,7}; q=ros_mixed({5,7.0})={10,21.0}; g={5,6,7};
    // sum = (5+7) + 21 + 10 + (5+6+7) = 61
    ok &= check("ros_roundtrip(5,7)", ros_roundtrip(5, 7), 61);

    printf(ok ? "ALL PASS\n" : "FAILURES\n");
    return ok ? 0 : 1;
}
